apiVersion: v1
appVersion: 10.0.0
description: Chart for deploying IBM Order Management System Enterprise Edition
icon: https://raw.githubusercontent.com/IBM/charts/master/logo/ibm-oms-logo.png
keywords:
- oms
- sterling
- yantra
- order
- fulfillment
- om
- amd64
- ppc64le
- framework
- Commercial
- ICP
kubeVersion: '>=1.11.3'
name: ibm-oms-ent-prod
tillerVersion: '>=2.9.1'
version: 2.0.0
